// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TerminalEngine>>
abstract class TerminalEngine implements RustOpaqueInterface {}

/// Color configuration passed from Dart at engine creation.
/// `palette` is length 18: [0..15] = ANSI colors, [16] = default fg, [17] = default bg
/// (each packed 0x00RRGGBB). `scrollback` = max history lines.
class EngineConfig {
  final Uint32List palette;
  final int scrollback;
  final int osc52;
  final String semanticEscapeChars;
  final int defaultCursorShape;
  final bool defaultCursorBlinking;

  const EngineConfig({
    required this.palette,
    required this.scrollback,
    required this.osc52,
    required this.semanticEscapeChars,
    required this.defaultCursorShape,
    required this.defaultCursorBlinking,
  });

  @override
  int get hashCode =>
      palette.hashCode ^
      scrollback.hashCode ^
      osc52.hashCode ^
      semanticEscapeChars.hashCode ^
      defaultCursorShape.hashCode ^
      defaultCursorBlinking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineConfig &&
          runtimeType == other.runtimeType &&
          palette == other.palette &&
          scrollback == other.scrollback &&
          osc52 == other.osc52 &&
          semanticEscapeChars == other.semanticEscapeChars &&
          defaultCursorShape == other.defaultCursorShape &&
          defaultCursorBlinking == other.defaultCursorBlinking;
}

/// Flat, columnar line for the FFI boundary. Storing each attribute in its own
/// primitive vector lets flutter_rust_bridge decode them as Dart typed lists
/// (`Uint32List` / `Uint16List`) in one shot — no per-cell Dart object is
/// allocated, unlike a `Vec<CellData>` which materializes one object per column.
/// Built internally from `Vec<CellData>` (which keeps the ergonomic per-cell
/// engine logic) and packed only at the boundary via [`LineUpdate::from_cells`].
class LineUpdate {
  final int line;
  final Uint32List codepoints;
  final Uint32List fg;
  final Uint32List bg;
  final Uint16List flags;
  final Uint32List hyperlinkId;

  const LineUpdate({
    required this.line,
    required this.codepoints,
    required this.fg,
    required this.bg,
    required this.flags,
    required this.hyperlinkId,
  });

  @override
  int get hashCode =>
      line.hashCode ^
      codepoints.hashCode ^
      fg.hashCode ^
      bg.hashCode ^
      flags.hashCode ^
      hyperlinkId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineUpdate &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          codepoints == other.codepoints &&
          fg == other.fg &&
          bg == other.bg &&
          flags == other.flags &&
          hyperlinkId == other.hyperlinkId;
}

class RenderUpdate {
  final List<LineUpdate> lines;
  final bool full;
  final int cursorLine;
  final int cursorCol;
  final bool cursorVisible;
  final int cursorShape;
  final bool cursorBlinking;
  final int modeFlags;
  final int displayOffset;

  /// Scrollback lines above the viewport (`total_lines - screen_lines`).
  final int historySize;
  final int defaultFg;
  final int defaultBg;
  final int cursorColor;

  /// Sub-cell scroll position in [0.0, 1.0): how far, in fractions of a cell
  /// height, the viewport is scrolled up past `display_offset`. The painter
  /// shifts content DOWN by `scroll_fraction * cell_height` and fills the
  /// revealed top sliver with the overscan row (the last entry in `lines` on
  /// a full update). 0.0 when sitting on a line boundary.
  final double scrollFraction;

  /// Net viewport line scroll since the last mirror state. Positive = scrolled
  /// up into history. Zero on full updates and on sub-cell-only pixel scrolls.
  /// The Dart mirror rotates existing rows by this delta before applying
  /// [lines], so scroll refresh only ships the edge rows that entered view.
  final int scrollLineDelta;

  const RenderUpdate({
    required this.lines,
    required this.full,
    required this.cursorLine,
    required this.cursorCol,
    required this.cursorVisible,
    required this.cursorShape,
    required this.cursorBlinking,
    required this.modeFlags,
    required this.displayOffset,
    required this.historySize,
    required this.defaultFg,
    required this.defaultBg,
    required this.cursorColor,
    required this.scrollFraction,
    required this.scrollLineDelta,
  });

  @override
  int get hashCode =>
      lines.hashCode ^
      full.hashCode ^
      cursorLine.hashCode ^
      cursorCol.hashCode ^
      cursorVisible.hashCode ^
      cursorShape.hashCode ^
      cursorBlinking.hashCode ^
      modeFlags.hashCode ^
      displayOffset.hashCode ^
      historySize.hashCode ^
      defaultFg.hashCode ^
      defaultBg.hashCode ^
      cursorColor.hashCode ^
      scrollFraction.hashCode ^
      scrollLineDelta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderUpdate &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          full == other.full &&
          cursorLine == other.cursorLine &&
          cursorCol == other.cursorCol &&
          cursorVisible == other.cursorVisible &&
          cursorShape == other.cursorShape &&
          cursorBlinking == other.cursorBlinking &&
          modeFlags == other.modeFlags &&
          displayOffset == other.displayOffset &&
          historySize == other.historySize &&
          defaultFg == other.defaultFg &&
          defaultBg == other.defaultBg &&
          cursorColor == other.cursorColor &&
          scrollFraction == other.scrollFraction &&
          scrollLineDelta == other.scrollLineDelta;
}
