// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TerminalEngine>>
abstract class TerminalEngine implements RustOpaqueInterface {}

/// Flat, FFI-friendly cell. fg/bg are packed 0x00RRGGBB.
class CellData {
  final int codepoint;
  final int fg;
  final int bg;
  final int flags;

  const CellData({
    required this.codepoint,
    required this.fg,
    required this.bg,
    required this.flags,
  });

  @override
  int get hashCode =>
      codepoint.hashCode ^ fg.hashCode ^ bg.hashCode ^ flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CellData &&
          runtimeType == other.runtimeType &&
          codepoint == other.codepoint &&
          fg == other.fg &&
          bg == other.bg &&
          flags == other.flags;
}

/// Color configuration passed from Dart at engine creation.
/// `palette` is length 18: [0..15] = ANSI colors, [16] = default fg, [17] = default bg
/// (each packed 0x00RRGGBB). `scrollback` = max history lines.
class EngineConfig {
  final Uint32List palette;
  final int scrollback;

  const EngineConfig({required this.palette, required this.scrollback});

  @override
  int get hashCode => palette.hashCode ^ scrollback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineConfig &&
          runtimeType == other.runtimeType &&
          palette == other.palette &&
          scrollback == other.scrollback;
}

class LineUpdate {
  final int line;
  final List<CellData> cells;

  const LineUpdate({required this.line, required this.cells});

  @override
  int get hashCode => line.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineUpdate &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          cells == other.cells;
}

class RenderUpdate {
  final List<LineUpdate> lines;
  final bool full;
  final int cursorLine;
  final int cursorCol;
  final bool cursorVisible;
  final int cursorShape;
  final bool cursorBlinking;
  final int modeFlags;
  final int displayOffset;

  const RenderUpdate({
    required this.lines,
    required this.full,
    required this.cursorLine,
    required this.cursorCol,
    required this.cursorVisible,
    required this.cursorShape,
    required this.cursorBlinking,
    required this.modeFlags,
    required this.displayOffset,
  });

  @override
  int get hashCode =>
      lines.hashCode ^
      full.hashCode ^
      cursorLine.hashCode ^
      cursorCol.hashCode ^
      cursorVisible.hashCode ^
      cursorShape.hashCode ^
      cursorBlinking.hashCode ^
      modeFlags.hashCode ^
      displayOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderUpdate &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          full == other.full &&
          cursorLine == other.cursorLine &&
          cursorCol == other.cursorCol &&
          cursorVisible == other.cursorVisible &&
          cursorShape == other.cursorShape &&
          cursorBlinking == other.cursorBlinking &&
          modeFlags == other.modeFlags &&
          displayOffset == other.displayOffset;
}
