// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'event_proxy.freezed.dart';

@freezed
sealed class EngineEvent with _$EngineEvent {
  const EngineEvent._();

  const factory EngineEvent.ptyWrite(Uint8List field0) = EngineEvent_PtyWrite;
  const factory EngineEvent.title(String field0) = EngineEvent_Title;
  const factory EngineEvent.resetTitle() = EngineEvent_ResetTitle;
  const factory EngineEvent.bell() = EngineEvent_Bell;
  const factory EngineEvent.clipboardStore(String field0) =
      EngineEvent_ClipboardStore;
  const factory EngineEvent.clipboardLoad() = EngineEvent_ClipboardLoad;

  /// OSC 7: current working directory (file://host/path).
  const factory EngineEvent.workingDir(String field0) = EngineEvent_WorkingDir;

  /// OSC 9 / OSC 777: desktop notification (body, or "title\0body" for 777).
  const factory EngineEvent.notify(String field0) = EngineEvent_Notify;
}
