// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/terminal.dart';
import 'dart:async';
import 'dart:convert';
import 'engine.dart';
import 'event_proxy.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -845402857;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_alacritty',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiTerminalEngineAdvance({
    required TerminalEngine engine,
    required List<int> bytes,
  });

  Future<RenderUpdate> crateApiTerminalEngineAdvanceAndTakeDamage({
    required TerminalEngine engine,
    required List<int> bytes,
  });

  RenderUpdate crateApiTerminalEngineFullSnapshot({
    required TerminalEngine engine,
  });

  TerminalEngine crateApiTerminalEngineNew({
    required int columns,
    required int rows,
    required EngineConfig config,
  });

  void crateApiTerminalEngineResize({
    required TerminalEngine engine,
    required int columns,
    required int rows,
  });

  Future<void> crateApiTerminalEngineScrollLines({
    required TerminalEngine engine,
    required int delta,
  });

  Future<void> crateApiTerminalEngineScrollToBottom({
    required TerminalEngine engine,
  });

  void crateApiTerminalEngineSelectionClear({required TerminalEngine engine});

  void crateApiTerminalEngineSelectionStart({
    required TerminalEngine engine,
    required int displayRow,
    required int col,
    required bool rightHalf,
    required int kind,
  });

  String? crateApiTerminalEngineSelectionText({required TerminalEngine engine});

  void crateApiTerminalEngineSelectionUpdate({
    required TerminalEngine engine,
    required int displayRow,
    required int col,
    required bool rightHalf,
  });

  Future<RenderUpdate> crateApiTerminalEngineTakeDamage({
    required TerminalEngine engine,
  });

  List<EngineEvent> crateApiTerminalEngineTakeEvents({
    required TerminalEngine engine,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TerminalEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TerminalEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TerminalEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiTerminalEngineAdvance({
    required TerminalEngine engine,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineAdvanceConstMeta,
        argValues: [engine, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineAdvanceConstMeta =>
      const TaskConstMeta(
        debugName: "engine_advance",
        argNames: ["engine", "bytes"],
      );

  @override
  Future<RenderUpdate> crateApiTerminalEngineAdvanceAndTakeDamage({
    required TerminalEngine engine,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_update,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineAdvanceAndTakeDamageConstMeta,
        argValues: [engine, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineAdvanceAndTakeDamageConstMeta =>
      const TaskConstMeta(
        debugName: "engine_advance_and_take_damage",
        argNames: ["engine", "bytes"],
      );

  @override
  RenderUpdate crateApiTerminalEngineFullSnapshot({
    required TerminalEngine engine,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_update,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineFullSnapshotConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineFullSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "engine_full_snapshot",
        argNames: ["engine"],
      );

  @override
  TerminalEngine crateApiTerminalEngineNew({
    required int columns,
    required int rows,
    required EngineConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(columns, serializer);
          sse_encode_u_16(rows, serializer);
          sse_encode_box_autoadd_engine_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineNewConstMeta,
        argValues: [columns, rows, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineNewConstMeta => const TaskConstMeta(
    debugName: "engine_new",
    argNames: ["columns", "rows", "config"],
  );

  @override
  void crateApiTerminalEngineResize({
    required TerminalEngine engine,
    required int columns,
    required int rows,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          sse_encode_u_16(columns, serializer);
          sse_encode_u_16(rows, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineResizeConstMeta,
        argValues: [engine, columns, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineResizeConstMeta =>
      const TaskConstMeta(
        debugName: "engine_resize",
        argNames: ["engine", "columns", "rows"],
      );

  @override
  Future<void> crateApiTerminalEngineScrollLines({
    required TerminalEngine engine,
    required int delta,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          sse_encode_i_32(delta, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineScrollLinesConstMeta,
        argValues: [engine, delta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineScrollLinesConstMeta =>
      const TaskConstMeta(
        debugName: "engine_scroll_lines",
        argNames: ["engine", "delta"],
      );

  @override
  Future<void> crateApiTerminalEngineScrollToBottom({
    required TerminalEngine engine,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineScrollToBottomConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineScrollToBottomConstMeta =>
      const TaskConstMeta(
        debugName: "engine_scroll_to_bottom",
        argNames: ["engine"],
      );

  @override
  void crateApiTerminalEngineSelectionClear({required TerminalEngine engine}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineSelectionClearConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineSelectionClearConstMeta =>
      const TaskConstMeta(
        debugName: "engine_selection_clear",
        argNames: ["engine"],
      );

  @override
  void crateApiTerminalEngineSelectionStart({
    required TerminalEngine engine,
    required int displayRow,
    required int col,
    required bool rightHalf,
    required int kind,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          sse_encode_i_32(displayRow, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_bool(rightHalf, serializer);
          sse_encode_u_8(kind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineSelectionStartConstMeta,
        argValues: [engine, displayRow, col, rightHalf, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineSelectionStartConstMeta =>
      const TaskConstMeta(
        debugName: "engine_selection_start",
        argNames: ["engine", "displayRow", "col", "rightHalf", "kind"],
      );

  @override
  String? crateApiTerminalEngineSelectionText({
    required TerminalEngine engine,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineSelectionTextConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineSelectionTextConstMeta =>
      const TaskConstMeta(
        debugName: "engine_selection_text",
        argNames: ["engine"],
      );

  @override
  void crateApiTerminalEngineSelectionUpdate({
    required TerminalEngine engine,
    required int displayRow,
    required int col,
    required bool rightHalf,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          sse_encode_i_32(displayRow, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_bool(rightHalf, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineSelectionUpdateConstMeta,
        argValues: [engine, displayRow, col, rightHalf],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineSelectionUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "engine_selection_update",
        argNames: ["engine", "displayRow", "col", "rightHalf"],
      );

  @override
  Future<RenderUpdate> crateApiTerminalEngineTakeDamage({
    required TerminalEngine engine,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_update,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineTakeDamageConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineTakeDamageConstMeta =>
      const TaskConstMeta(
        debugName: "engine_take_damage",
        argNames: ["engine"],
      );

  @override
  List<EngineEvent> crateApiTerminalEngineTakeEvents({
    required TerminalEngine engine,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
            engine,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_engine_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalEngineTakeEventsConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalEngineTakeEventsConstMeta =>
      const TaskConstMeta(
        debugName: "engine_take_events",
        argNames: ["engine"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TerminalEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TerminalEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine;

  @protected
  TerminalEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TerminalEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TerminalEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TerminalEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EngineConfig dco_decode_box_autoadd_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_engine_config(raw);
  }

  @protected
  CellData dco_decode_cell_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CellData(
      codepoint: dco_decode_u_32(arr[0]),
      fg: dco_decode_u_32(arr[1]),
      bg: dco_decode_u_32(arr[2]),
      flags: dco_decode_u_16(arr[3]),
    );
  }

  @protected
  EngineConfig dco_decode_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EngineConfig(
      palette: dco_decode_list_prim_u_32_strict(arr[0]),
      scrollback: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  EngineEvent dco_decode_engine_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return EngineEvent_PtyWrite(dco_decode_list_prim_u_8_strict(raw[1]));
      case 1:
        return EngineEvent_Title(dco_decode_String(raw[1]));
      case 2:
        return EngineEvent_ResetTitle();
      case 3:
        return EngineEvent_Bell();
      case 4:
        return EngineEvent_ClipboardStore(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LineUpdate dco_decode_line_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LineUpdate(
      line: dco_decode_u_32(arr[0]),
      cells: dco_decode_list_cell_data(arr[1]),
    );
  }

  @protected
  List<CellData> dco_decode_list_cell_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell_data).toList();
  }

  @protected
  List<EngineEvent> dco_decode_list_engine_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_engine_event).toList();
  }

  @protected
  List<LineUpdate> dco_decode_list_line_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_line_update).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RenderUpdate dco_decode_render_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RenderUpdate(
      lines: dco_decode_list_line_update(arr[0]),
      full: dco_decode_bool(arr[1]),
      cursorLine: dco_decode_u_32(arr[2]),
      cursorCol: dco_decode_u_32(arr[3]),
      cursorVisible: dco_decode_bool(arr[4]),
      cursorShape: dco_decode_u_8(arr[5]),
      cursorBlinking: dco_decode_bool(arr[6]),
      modeFlags: dco_decode_u_32(arr[7]),
      displayOffset: dco_decode_u_32(arr[8]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  TerminalEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TerminalEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TerminalEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TerminalEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TerminalEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EngineConfig sse_decode_box_autoadd_engine_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_engine_config(deserializer));
  }

  @protected
  CellData sse_decode_cell_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_codepoint = sse_decode_u_32(deserializer);
    var var_fg = sse_decode_u_32(deserializer);
    var var_bg = sse_decode_u_32(deserializer);
    var var_flags = sse_decode_u_16(deserializer);
    return CellData(
      codepoint: var_codepoint,
      fg: var_fg,
      bg: var_bg,
      flags: var_flags,
    );
  }

  @protected
  EngineConfig sse_decode_engine_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_palette = sse_decode_list_prim_u_32_strict(deserializer);
    var var_scrollback = sse_decode_u_32(deserializer);
    return EngineConfig(palette: var_palette, scrollback: var_scrollback);
  }

  @protected
  EngineEvent sse_decode_engine_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return EngineEvent_PtyWrite(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return EngineEvent_Title(var_field0);
      case 2:
        return EngineEvent_ResetTitle();
      case 3:
        return EngineEvent_Bell();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return EngineEvent_ClipboardStore(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LineUpdate sse_decode_line_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_line = sse_decode_u_32(deserializer);
    var var_cells = sse_decode_list_cell_data(deserializer);
    return LineUpdate(line: var_line, cells: var_cells);
  }

  @protected
  List<CellData> sse_decode_list_cell_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<EngineEvent> sse_decode_list_engine_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EngineEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_engine_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<LineUpdate> sse_decode_list_line_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LineUpdate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_line_update(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RenderUpdate sse_decode_render_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_line_update(deserializer);
    var var_full = sse_decode_bool(deserializer);
    var var_cursorLine = sse_decode_u_32(deserializer);
    var var_cursorCol = sse_decode_u_32(deserializer);
    var var_cursorVisible = sse_decode_bool(deserializer);
    var var_cursorShape = sse_decode_u_8(deserializer);
    var var_cursorBlinking = sse_decode_bool(deserializer);
    var var_modeFlags = sse_decode_u_32(deserializer);
    var var_displayOffset = sse_decode_u_32(deserializer);
    return RenderUpdate(
      lines: var_lines,
      full: var_full,
      cursorLine: var_cursorLine,
      cursorCol: var_cursorCol,
      cursorVisible: var_cursorVisible,
      cursorShape: var_cursorShape,
      cursorBlinking: var_cursorBlinking,
      modeFlags: var_modeFlags,
      displayOffset: var_displayOffset,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    TerminalEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TerminalEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    TerminalEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TerminalEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    TerminalEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TerminalEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEngine(
    TerminalEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TerminalEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_engine_config(
    EngineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_engine_config(self, serializer);
  }

  @protected
  void sse_encode_cell_data(CellData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.codepoint, serializer);
    sse_encode_u_32(self.fg, serializer);
    sse_encode_u_32(self.bg, serializer);
    sse_encode_u_16(self.flags, serializer);
  }

  @protected
  void sse_encode_engine_config(EngineConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_32_strict(self.palette, serializer);
    sse_encode_u_32(self.scrollback, serializer);
  }

  @protected
  void sse_encode_engine_event(EngineEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case EngineEvent_PtyWrite(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
      case EngineEvent_Title(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case EngineEvent_ResetTitle():
        sse_encode_i_32(2, serializer);
      case EngineEvent_Bell():
        sse_encode_i_32(3, serializer);
      case EngineEvent_ClipboardStore(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_line_update(LineUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.line, serializer);
    sse_encode_list_cell_data(self.cells, serializer);
  }

  @protected
  void sse_encode_list_cell_data(
    List<CellData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_engine_event(
    List<EngineEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_engine_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_line_update(
    List<LineUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_line_update(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_render_update(RenderUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_line_update(self.lines, serializer);
    sse_encode_bool(self.full, serializer);
    sse_encode_u_32(self.cursorLine, serializer);
    sse_encode_u_32(self.cursorCol, serializer);
    sse_encode_bool(self.cursorVisible, serializer);
    sse_encode_u_8(self.cursorShape, serializer);
    sse_encode_bool(self.cursorBlinking, serializer);
    sse_encode_u_32(self.modeFlags, serializer);
    sse_encode_u_32(self.displayOffset, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class TerminalEngineImpl extends RustOpaque implements TerminalEngine {
  // Not to be used by end users
  TerminalEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TerminalEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TerminalEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TerminalEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TerminalEnginePtr,
  );
}
