// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

TerminalEngine engineNew({required int columns, required int rows}) => RustLib
    .instance
    .api
    .crateApiTerminalEngineNew(columns: columns, rows: rows);

void engineAdvance({
  required TerminalEngine engine,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalEngineAdvance(
  engine: engine,
  bytes: bytes,
);

RenderSnapshot engineSnapshot({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSnapshot(engine: engine);

void engineResize({
  required TerminalEngine engine,
  required int columns,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalEngineResize(
  engine: engine,
  columns: columns,
  rows: rows,
);
